{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeApiController","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeBridge","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeConfig","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeCore"]},{"identifiers":["doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/AdMobAds","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/AdMobData","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/Appsflyer","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/BiometricAuth","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/ButtonData","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/CustomUserAgent","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/Element","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/NavigationLoader","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/NoInternetData","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/Onboarding","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/Page","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/PageIndicator","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/RegexInternalExternal","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/RegexInternalExternalRule","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/SocialLogin","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/StickyFooter","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/StickyFooterButton","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/StickyFooterData","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeConfigData"],"title":"Structures"},{"identifiers":["doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/AdPosition","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/AdType","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/ElementType","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/LinkHandleType","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/NavigationLoaderAnimationShape","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/NavigationLoaderAnimationSize","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/NavigationLoaderType","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/OrientationType","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/UserAgentType"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/Swift"]}],"metadata":{"externalID":"WebToNativeCore","roleHeading":"Framework","title":"WebToNativeCore","modules":[{"name":"WebToNativeCore"}],"role":"collection","symbolKind":"module"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[[]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/webtonativecore"]},{"paths":["\/documentation\/webtonativecore"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/LinkHandleType":{"url":"\/documentation\/webtonativecore\/linkhandletype","kind":"symbol","title":"LinkHandleType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LinkHandleType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/LinkHandleType","role":"symbol","navigatorTitle":[{"text":"LinkHandleType","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/RegexInternalExternalRule":{"title":"RegexInternalExternalRule","type":"topic","url":"\/documentation\/webtonativecore\/regexinternalexternalrule","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RegexInternalExternalRule","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RegexInternalExternalRule"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/RegexInternalExternalRule","role":"symbol"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/StickyFooter":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StickyFooter"}],"url":"\/documentation\/webtonativecore\/stickyfooter","navigatorTitle":[{"text":"StickyFooter","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/StickyFooter","title":"StickyFooter","role":"symbol"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/WebToNativeCoreVersionString":{"title":"WebToNativeCoreVersionString","kind":"symbol","abstract":[],"url":"\/documentation\/webtonativecore\/webtonativecoreversionstring","role":"symbol","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeCoreVersionString","fragments":[{"text":"WebToNativeCoreVersionString","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/WebToNativeConfigData":{"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeConfigData","url":"\/documentation\/webtonativecore\/webtonativeconfigdata","abstract":[{"type":"text","text":"Represents the configuration data structure for the WebToNative application."}],"role":"symbol","navigatorTitle":[{"text":"WebToNativeConfigData","kind":"identifier"}],"kind":"symbol","title":"WebToNativeConfigData","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"WebToNativeConfigData","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/NavigationLoader":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"NavigationLoader","kind":"identifier"}],"navigatorTitle":[{"text":"NavigationLoader","kind":"identifier"}],"url":"\/documentation\/webtonativecore\/navigationloader","type":"topic","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/NavigationLoader","abstract":[],"role":"symbol","title":"NavigationLoader","kind":"symbol"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/UserAgentType":{"type":"topic","title":"UserAgentType","kind":"symbol","role":"symbol","url":"\/documentation\/webtonativecore\/useragenttype","navigatorTitle":[{"text":"UserAgentType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"UserAgentType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/UserAgentType"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/WebToNativeCore":{"url":"\/documentation\/webtonativecore\/webtonativecore","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebToNativeCore"}],"title":"WebToNativeCore","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeCore","role":"symbol","abstract":[{"type":"text","text":"Core class responsible for handling communication with the web view in the WebToNative application."}],"navigatorTitle":[{"kind":"identifier","text":"WebToNativeCore"}],"kind":"symbol"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/AdType":{"title":"AdType","abstract":[],"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/AdType","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AdType"}],"url":"\/documentation\/webtonativecore\/adtype","type":"topic"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/StickyFooterData":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"StickyFooterData","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"StickyFooterData","kind":"identifier"}],"kind":"symbol","title":"StickyFooterData","type":"topic","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/StickyFooterData","url":"\/documentation\/webtonativecore\/stickyfooterdata"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/NavigationLoaderType":{"kind":"symbol","role":"symbol","title":"NavigationLoaderType","abstract":[],"url":"\/documentation\/webtonativecore\/navigationloadertype","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/NavigationLoaderType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NavigationLoaderType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NavigationLoaderType"}]},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/Onboarding":{"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/Onboarding","role":"symbol","url":"\/documentation\/webtonativecore\/onboarding","title":"Onboarding","navigatorTitle":[{"kind":"identifier","text":"Onboarding"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Onboarding"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/StickyFooterButton":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StickyFooterButton"}],"title":"StickyFooterButton","abstract":[],"url":"\/documentation\/webtonativecore\/stickyfooterbutton","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/StickyFooterButton","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StickyFooterButton"}]},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/WebToNativeApiController":{"navigatorTitle":[{"kind":"identifier","text":"WebToNativeApiController"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeApiController","kind":"symbol","url":"\/documentation\/webtonativecore\/webtonativeapicontroller","role":"symbol","title":"WebToNativeApiController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WebToNativeApiController","kind":"identifier"}],"abstract":[{"text":"Utility class for making HTTP POST requests to a specified URL with JSON data.","type":"text"}]},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/OrientationType":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OrientationType"}],"url":"\/documentation\/webtonativecore\/orientationtype","navigatorTitle":[{"text":"OrientationType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/OrientationType","title":"OrientationType","role":"symbol"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/BiometricAuth":{"type":"topic","title":"BiometricAuth","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BiometricAuth","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BiometricAuth","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/BiometricAuth","url":"\/documentation\/webtonativecore\/biometricauth"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/SocialLogin":{"role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/SocialLogin","title":"SocialLogin","type":"topic","url":"\/documentation\/webtonativecore\/sociallogin","navigatorTitle":[{"text":"SocialLogin","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLogin","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/WebToNativeConfig":{"url":"\/documentation\/webtonativecore\/webtonativeconfig","kind":"symbol","title":"WebToNativeConfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WebToNativeConfig","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the configuration manager for WebToNative."}],"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeConfig","role":"symbol","navigatorTitle":[{"text":"WebToNativeConfig","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/AdMobData":{"url":"\/documentation\/webtonativecore\/admobdata","abstract":[],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdMobData"}],"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/AdMobData","title":"AdMobData","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdMobData"}]},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/WebToNativeCoreVersionNumber":{"type":"topic","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeCoreVersionNumber","kind":"symbol","url":"\/documentation\/webtonativecore\/webtonativecoreversionnumber","role":"symbol","title":"WebToNativeCoreVersionNumber","fragments":[{"kind":"identifier","text":"WebToNativeCoreVersionNumber"}],"abstract":[]},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/AdMobAds":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/AdMobAds","abstract":[],"title":"AdMobAds","type":"topic","url":"\/documentation\/webtonativecore\/admobads","navigatorTitle":[{"text":"AdMobAds","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdMobAds","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore":{"kind":"symbol","role":"collection","title":"WebToNativeCore","abstract":[],"url":"\/documentation\/webtonativecore","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore","type":"topic"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/AdPosition":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdPosition","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/AdPosition","role":"symbol","url":"\/documentation\/webtonativecore\/adposition","type":"topic","title":"AdPosition","abstract":[],"navigatorTitle":[{"text":"AdPosition","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/NoInternetData":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"NoInternetData","kind":"identifier"}],"title":"NoInternetData","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"NoInternetData"}],"url":"\/documentation\/webtonativecore\/nointernetdata","kind":"symbol","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/NoInternetData"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/CustomUserAgent":{"kind":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomUserAgent","kind":"identifier"}],"url":"\/documentation\/webtonativecore\/customuseragent","navigatorTitle":[{"kind":"identifier","text":"CustomUserAgent"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/CustomUserAgent","title":"CustomUserAgent","role":"symbol"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/RegexInternalExternal":{"type":"topic","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/RegexInternalExternal","kind":"symbol","abstract":[],"title":"RegexInternalExternal","role":"symbol","url":"\/documentation\/webtonativecore\/regexinternalexternal","navigatorTitle":[{"kind":"identifier","text":"RegexInternalExternal"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RegexInternalExternal","kind":"identifier"}]},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/Page":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Page"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/Page","url":"\/documentation\/webtonativecore\/page","type":"topic","role":"symbol","navigatorTitle":[{"text":"Page","kind":"identifier"}],"title":"Page"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/NavigationLoaderAnimationSize":{"abstract":[],"title":"NavigationLoaderAnimationSize","type":"topic","url":"\/documentation\/webtonativecore\/navigationloaderanimationsize","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NavigationLoaderAnimationSize"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/NavigationLoaderAnimationSize","navigatorTitle":[{"kind":"identifier","text":"NavigationLoaderAnimationSize"}],"role":"symbol"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/WebToNativeBridge":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WebToNativeBridge"}],"navigatorTitle":[{"text":"WebToNativeBridge","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Class responsible for managing communication between the web view and native modules."}],"url":"\/documentation\/webtonativecore\/webtonativebridge","title":"WebToNativeBridge","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeBridge"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/PageIndicator":{"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/PageIndicator","abstract":[],"title":"PageIndicator","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PageIndicator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/webtonativecore\/pageindicator","role":"symbol","navigatorTitle":[{"text":"PageIndicator","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/Appsflyer":{"url":"\/documentation\/webtonativecore\/appsflyer","type":"topic","title":"Appsflyer","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/Appsflyer","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Appsflyer","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Appsflyer","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/ElementType":{"role":"symbol","title":"ElementType","navigatorTitle":[{"text":"ElementType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ElementType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/ElementType","kind":"symbol","url":"\/documentation\/webtonativecore\/elementtype","abstract":[]},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/Element":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Element"}],"title":"Element","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Element"}],"url":"\/documentation\/webtonativecore\/element","kind":"symbol","identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/Element"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/NavigationLoaderAnimationShape":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NavigationLoaderAnimationShape","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NavigationLoaderAnimationShape"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/NavigationLoaderAnimationShape","url":"\/documentation\/webtonativecore\/navigationloaderanimationshape","title":"NavigationLoaderAnimationShape"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/Swift":{"url":"\/documentation\/webtonativecore\/swift","role":"collection","kind":"symbol","title":"Swift","abstract":[],"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/Swift","type":"topic"},"doc://org.cocoapods.WebToNativeCore/documentation/WebToNativeCore/ButtonData":{"identifier":"doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/ButtonData","kind":"symbol","title":"ButtonData","url":"\/documentation\/webtonativecore\/buttondata","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"ButtonData","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ButtonData","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeCoreVersionNumber","doc:\/\/org.cocoapods.WebToNativeCore\/documentation\/WebToNativeCore\/WebToNativeCoreVersionString"],"title":"Variables"}],"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"}]}]}